### ISSUE TITLE
Add 'cssmin' to requirements.txt

### ISSUE THREAD

**Issue by srid** [hyde/hyde-old#57]
```
$ python hyde.py  -g -s ~/blog -d ~/blog-deploy 
INFO:Pre processing /Users/user/blog[2011-02-05 16:51:40,922]
INFO:Processing /index.html[2011-02-05 16:51:40,923]
INFO:Processing /about/about.html[2011-02-05 16:51:41,385]
INFO:Processing /archives/firstpost.html[2011-02-05 16:51:41,413]
INFO:Processing /archives/archives.html[2011-02-05 16:51:41,426]
INFO:Processing /media/css/base.css[2011-02-05 16:51:41,438]
Generation Failed
Traceback (most recent call last):
  File "/Users/sridharr/code/hyde/hydeengine/__init__.py", line 417, in process_all
    self.process(resource)
  File "/Users/sridharr/code/hyde/hydeengine/__init__.py", line 377, in process
    return self.processor.process(item)
  File "/Users/sridharr/code/hyde/hydeengine/processor.py", line 111, in process
    processor.process(resource)
  File "/Users/sridharr/code/hyde/hydeengine/media_processors.py", line 102, in process
    import cssmin
ImportError: No module named cssmin
```

**Comment by valpackett** [comment]
cssmin is optional. Not everybody needs it.

Maybe create "recommended.txt"?

**Comment by srid** [comment]
> cssmin is optional. Not everybody needs it.

If it is optional, then why does the default example mentioned in README fail to run? To explain, I followed the "Running with Hyde" section, specifically step 1 (Initializer) and 2 (Generator).

> Maybe create "recommended.txt"?

I suggest that the optional dependencies be put in setup.py as `extras_require`. See [the documentation](http://packages.python.org/distribute/setuptools.html#declaring-extras) or SQLObject's setup.py for an example.

**Comment by navilan** [comment]
yeah - recommended seems like a good idea. Will do.

**Comment by zenbum** [comment]
What @srid said. The README example failing first-hand really gives a bad first impression...
