### ISSUE TITLE
how do i set up a new install

### ISSUE THREAD

**Issue by saras** [hyde/hyde-old#81]
Traceback (most recent call last):
  File "hyde.py", line 8, in <module>
    import hydeengine
  File "/media/8b6fa65e-c3d4-4d90-afbd-9cccb712e0d5/nova site/hyde/hydeengine/**init**.py", line 17, in <module>
    from django.conf import settings
ImportError: No module named django.conf
how do i make a django.conf

**Comment by navilan** [comment]
Hello - this repository is obsolete. Please use http://github.com/hyde/hyde.
